---
language: node_js
node_js:
  - "8"

notifications:
  email: true

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - npm config set spin false
  - yarn global add greenkeeper-lockfile@1

script:
- yarn run build
- yarn test
- yarn run lint

before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

deploy:
  provider: surge
  project: ./dist/
  domain: redtn-ember.surge.sh
  skip_cleanup: true
